### ISSUE TITLE
dbp dataset

### ISSUE THREAD

**Issue by lalalei21** [koustuvsinha/hier-class#4]
Hi, I download the dbp dataset and find it has only 342,782 documents, which is less than your given in the paper. Is that all?

**Comment by koustuvsinha** [comment]
Hi @lalalei21 , yes that is the cleaned version of the dataset after cleaning and balancing the classes. I think we may have missed to update the final numbers in the paper - I will update it in our next arxiv revision. Thanks for pointing it out!

**Comment by lalalei21** [comment]
@koustuvsinha Thanks for your reply!
I have another question. 
Your code prints "Model Parameters: 50682922", but the experimental results show the 34M parameters. 
Whether the word embedding parameters are excluded or there are other reasons.
